docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v3
  versions:
    - v3
nav:
  - Home: index.md
  - v3:
      - Overview: v5/overview.md
      - Installation: v5/installation.md
      - Usage: v5/usage.md
      - Factories: v5/factories.md
      - Reference:
          - "Inject class dependencies": v5/factories/service.md
          - "Inject entity repositories": v5/factories/repository.md
site_name: dot-cli
site_description: "DotKernel's component to build console applications"
repo_url: "https://github.com/dotkernel/dot-cli"
plugins:
  - search
