docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v3
  versions:
    - v3
nav:
  - Home: index.md
  - v3:
      - Configuration: v3/configuration.md
      - Installation: v3/installation.md
      - "Setting Up As Cronjob": v3/setting-up-as-cronjob.md
      - Testing: v3/testing.md
      - Usage: v3/usage.md
site_name: dot-cli
site_description: "DotKernel's component to build console applications"
repo_url: "https://github.com/dotkernel/dot-cli"
plugins:
  - search
